// Converts a 5×7 BDF font to a synth-ui bitmap face: printable ASCII plus the
// few symbols the site's text uses.
//
// The face in src/web/canvas/mixedFont.ts comes from the X.org misc-fixed
// 5x7 font, which is in the public domain ("Public domain font. Share and
// enjoy."): https://gitlab.freedesktop.org/xorg/font/misc-misc/-/raw/master/5x7.bdf
//
// Usage: node scripts/bdf-to-face.mjs 5x7.bdf > src/web/canvas/mixedFont.ts

import { readFileSync } from "node:fs";

/** · – — … ÷ × © ↑ ↓ ▲ ▼ */
const EXTRA = [0xb7, 0x2013, 0x2014, 0x2026, 0xf7, 0xd7, 0xa9, 0x2191, 0x2193, 0x25b2, 0x25bc];

const WIDTH = 5;
const HEIGHT = 7;

const bdf = readFileSync(process.argv[2], "utf8");
const box = /^FONTBOUNDINGBOX (\d+) (\d+) (-?\d+) (-?\d+)$/m.exec(bdf);
if (!box || Number(box[1]) !== WIDTH || Number(box[2]) !== HEIGHT) throw new Error("expected a 5×7 font");
const descent = -Number(box[4]);
const ascent = HEIGHT - descent;

const glyphs = new Map();
for (const block of bdf.split("STARTCHAR").slice(1)) {
  const code = Number(/^ENCODING (\d+)$/m.exec(block)?.[1]);
  if (!((code >= 0x20 && code <= 0x7e) || EXTRA.includes(code))) continue;
  const [w, h, xoff, yoff] = /^BBX (\d+) (\d+) (-?\d+) (-?\d+)$/m.exec(block).slice(1).map(Number);
  const rows = block.split(/^BITMAP$/m)[1].split(/^ENDCHAR$/m)[0].trim().split(/\s+/).filter(Boolean);
  const cell = Array.from({ length: HEIGHT }, () => Array(WIDTH).fill("."));
  rows.forEach((hex, r) => {
    const bits = parseInt(hex, 16);
    const bitCount = hex.length * 4;
    const y = yoff + h - 1 - r; // baseline at 0, up is positive
    const row = ascent - 1 - y;
    for (let c = 0; c < w; c++) {
      if (bits & (1 << (bitCount - 1 - c))) cell[row][xoff + c] = "#";
    }
  });
  glyphs.set(String.fromCharCode(code), cell.map((row) => row.join("")).join(" "));
}
if (glyphs.size !== 95 + EXTRA.length) throw new Error(`expected ${95 + EXTRA.length} glyphs, got ${glyphs.size}`);

const lines = [...glyphs].map(([char, rows]) => `    ${JSON.stringify(char)}: ${JSON.stringify(rows)},`);
process.stdout.write(`// Generated by scripts/bdf-to-face.mjs from the X.org misc-fixed 5x7 font.
// That font is in the public domain: "Public domain font. Share and enjoy."
// Do not edit by hand.

import type { BitmapFace } from "@synth-ui/core";

/** A 5×7 monospaced face with lowercase, for text whose case matters: receipts, item names. */
export const MIXED_5X7: BitmapFace = {
  kind: "bitmap",
  fallback: "?",
  glyphs: {
${lines.join("\n")}
  },
};
`);
