// Builds the Chinese, Japanese and Korean bitmap faces from Fusion Pixel Font
// 8px (proportional), each cut down to the characters its catalogue uses.
//
// Fusion Pixel Font is © TakWolf and licensed under the SIL Open Font License 1.1
// (with its source fonts' licences, all permitting modification and
// redistribution): https://github.com/TakWolf/fusion-pixel-font
//
// Usage: node scripts/cjk-faces.mjs <dir with fusion-pixel-8px-proportional-*.bdf>
// Run it again after changing a translation; the font tests fail until you do.

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const FACES = [
  { locale: "zh-Hans", bdf: "zh_hans", name: "CJK_ZH_HANS", file: "cjkZhHans" },
  { locale: "zh-Hant", bdf: "zh_hant", name: "CJK_ZH_HANT", file: "cjkZhHant" },
  { locale: "ja", bdf: "ja", name: "CJK_JA", file: "cjkJa" },
  { locale: "ko", bdf: "ko", name: "CJK_KO", file: "cjkKo" },
];

/** Characters every face needs whatever its catalogue says: what data and the canvas draw. */
const BASE = [...[...Array(95).keys()].map((i) => String.fromCharCode(0x20 + i)), ..."·–—…÷×©↑↓▲▼"];

function parseBdf(text) {
  const ascent = Number(/^FONT_ASCENT (\d+)$/m.exec(text)[1]);
  const descent = Number(/^FONT_DESCENT (\d+)$/m.exec(text)[1]);
  const glyphs = new Map();
  for (const block of text.split("STARTCHAR").slice(1)) {
    const code = Number(/^ENCODING (-?\d+)$/m.exec(block)?.[1]);
    if (!(code >= 0)) continue;
    const advance = Number(/^DWIDTH (\d+) /m.exec(block)[1]);
    const [w, h, xoff, yoff] = /^BBX (\d+) (\d+) (-?\d+) (-?\d+)$/m.exec(block).slice(1).map(Number);
    const rows = (block.split(/^BITMAP$/m)[1] ?? "").split(/^ENDCHAR$/m)[0].trim().split(/\s+/).filter(Boolean);
    glyphs.set(code, { advance, w, h, xoff, yoff, rows });
  }
  return { ascent, descent, glyphs };
}

/** A glyph as cell rows of # and ., `advance` wide and `ascent + descent` tall. */
function cell(glyph, ascent, descent) {
  const height = ascent + descent;
  const grid = Array.from({ length: height }, () => Array(glyph.advance).fill("."));
  glyph.rows.forEach((hex, r) => {
    const bits = BigInt(`0x${hex}`);
    const bitCount = BigInt(hex.length * 4);
    const y = glyph.yoff + glyph.h - 1 - r;
    const row = ascent - 1 - y;
    for (let c = 0; c < glyph.w; c++) {
      if (bits & (1n << (bitCount - 1n - BigInt(c)))) {
        const x = glyph.xoff + c;
        if (row >= 0 && row < height && x >= 0 && x < glyph.advance) grid[row][x] = "#";
      }
    }
  });
  return grid;
}

const dir = process.argv[2];
if (!dir) throw new Error("usage: node scripts/cjk-faces.mjs <fusion-pixel-font-8px-proportional-bdf dir>");

for (const face of FACES) {
  const catalogue = readFileSync(new URL(`../src/web/i18n/${face.locale}.ts`, import.meta.url), "utf8");
  const chars = [...new Set([...BASE, ...[...catalogue].filter((c) => c.codePointAt(0) > 0x7e && !/\s/.test(c))])].sort();
  const font = parseBdf(readFileSync(join(dir, `fusion-pixel-8px-proportional-${face.bdf}.bdf`), "utf8"));
  const missing = chars.filter((c) => !font.glyphs.has(c.codePointAt(0)));
  if (missing.length > 0) throw new Error(`${face.locale}: the font has no glyph for ${missing.join(" ")}`);

  const cells = chars.map((c) => [c, cell(font.glyphs.get(c.codePointAt(0)), font.ascent, font.descent)]);
  // Trim rows no chosen glyph uses, top and bottom, keeping every glyph aligned.
  const inked = (row) => cells.some(([, grid]) => grid[row].includes("#"));
  let top = 0;
  while (top < font.ascent + font.descent - 1 && !inked(top)) top++;
  let bottom = font.ascent + font.descent - 1;
  while (bottom > top && !inked(bottom)) bottom--;

  const lines = cells.map(([c, grid]) => {
    const rows = grid.slice(top, bottom + 1).map((row) => row.join("")).join(" ");
    return `    ${JSON.stringify(c)}: ${JSON.stringify(rows)},`;
  });
  writeFileSync(
    new URL(`../src/web/canvas/fonts/${face.file}.ts`, import.meta.url),
    `// Generated by scripts/cjk-faces.mjs from Fusion Pixel Font 8px (proportional), ${face.bdf}.
// © TakWolf, SIL Open Font License 1.1: see public/licenses/fusion-pixel/.
// Only the characters src/web/i18n/${face.locale}.ts uses, plus ASCII. Do not edit by hand.

import type { BitmapFace } from "@synth-ui/core";

export const ${face.name}: BitmapFace = {
  kind: "bitmap",
  spacing: 0,
  fallback: "?",
  glyphs: {
${lines.join("\n")}
  },
};
`,
  );
  console.log(`${face.locale}: ${cells.length} glyphs, ${bottom - top + 1} rows tall`);
}
